on:
  push:
    branches: [ "development" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4


      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.0"
          channel: stable

      - name: Install dependencies
        run: flutter pub get


      - name: Analyze project source
        run: flutter analyze

      - name: Ensure App Builds
        run: flutter build apk --debug
